export enum CategoriaProveedor {
  FERRETERIA = 'FERRETERIA',
  PLOMERIA = 'PLOMERIA',
  ELECTRICIDAD = 'ELECTRICIDAD',
  CONSTRUCCION = 'CONSTRUCCION',
  PINTURAS = 'PINTURAS',
  HERRAMIENTAS = 'HERRAMIENTAS',
  SEGURIDAD = 'SEGURIDAD',
  JARDINERIA = 'JARDINERIA',
  OTROS = 'OTROS',
}


