export enum TipoMovimientoCC {
  FACTURA = 'FACTURA',
  REMITO = 'REMITO',
  NOTA_DEBITO = 'NOTA_DEBITO',
  NOTA_CREDITO = 'NOTA_CREDITO',
  PAGO_PARCIAL = 'PAGO_PARCIAL',
  PAGO_COMPLETO = 'PAGO_COMPLETO',
  GASTO = 'GASTO',
}


